import{t as S,g as k}from"./assets/theme-module-c1919ebf.js";import{A as q,S as F,N as C,K as M,i as m,a as w}from"./assets/vendor-6128a7b9.js";const x=document.querySelector(".faq__list");new q(x,{elementClass:"faq__item",triggerClass:"faq__btn",panelClass:"ac-panel",activeClass:"is-active",openOnInit:[0],onOpen:e=>{}});const A=document.querySelectorAll('[name="slider"]'),I=document.querySelector(".mob-menu-btn"),B=document.querySelector(".mob-menu-btn-close"),l=document.querySelector(".mob-menu");document.querySelector(".header-nav-menu");const _=document.querySelectorAll('a[href*="#"]');for(let e of _)e.addEventListener("click",function(t){t.preventDefault();const s=e.getAttribute("href").substr(1);document.getElementById(s).scrollIntoView({behavior:"smooth",block:"start"})});for(let e of A)e.addEventListener("click",t=>{S()});I.addEventListener("click",e=>{l.classList.add("is-open")});B.addEventListener("click",e=>{l.classList.remove("is-open")});l.addEventListener("click",e=>{const t=e.target.name;if(t==="About me"||t==="Projects"||t==="Contacts")l.classList.remove("is-open");else return});const c=document.getElementById("two-button"),d=document.querySelectorAll("#list-sites .hidden");let r=0;function g(){r>=d.length?c.style.display="none":c.style.display="block"}g();c.addEventListener("click",()=>{let e=3;for(let t=r;t<r+e&&t<d.length;t++)d[t].classList.remove("hidden");r+=e,g()});const b=document.querySelector("#swiper-container"),p=new F(".swiper",{modules:[C,M],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,breakpoints:{1280:{slidesPerView:2},0:{slidesPerView:"auto"}},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});document.addEventListener("keydown",e=>{e.key==="Tab"&&b.contains(document.activeElement)&&(e.shiftKey?p.slidePrev():p.slideNext())});const L=document.querySelector(".loader");function T(){L.style.display="none"}function j(){L.style.visibility="visible"}const P="https://portfolio-js.b.goit.study/api/reviews",v=document.querySelector(".swiper-wrapper");async function N(){return(await w.get(P,{})).data}function R(e){return e.map(t=>`
      <li class="swiper-slide" id="review-slide">

      <p class="reviews-text">${t.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${t.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${t.avatar_url}"/>
          </a>
          <p class="reviews-name">${t.author}</p>
      </div>
      </li>`).join("")}const y=document.querySelector(".error-container");j();N().then(e=>{y.style.display="none",e.length>0?v.insertAdjacentHTML("beforeend",R(e)):(v.insertAdjacentHTML("beforeend","Not found"),m.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(e=>{b.style.display="none",y.insertAdjacentHTML("beforeend","<p>Not found</p>"),m.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}),console.log(e)}).finally(()=>{T()});const i=document.querySelector(".work-together-form"),a=i.elements.email,W=i.elements.message,o=document.querySelector(".modal"),$=o.querySelector(".button-close"),h=o.querySelector(".modal-backdrop"),f=document.getElementById("email-error"),n=document.querySelector(".icon-email"),H=w.create({baseURL:"https://portfolio-js.b.goit.study/api-docs"});o.classList.add("visually-hidden");n.classList.add("visually-hidden");async function V(e,t){try{return(await H.post("",{email:e,message:t})).data}catch(s){throw s}}function E(e){return/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(e)}i.addEventListener("input",e=>{const t=a.value.trim();n.classList.add("visually-hidden"),E(t)&&n.classList.remove("visually-hidden")});i.addEventListener("submit",async e=>{e.preventDefault();const t=a.value.trim(),s=W.value.trim();if(f.textContent="",a.classList.remove("invalid-input"),t===""||s===""){alert("Будь ласка, заповніть всі поля.");return}if(E(t))n.classList.remove("visually-hidden");else{f.textContent="Invalid email, try again",a.classList.add("invalid-input");return}try{await V(t,s),z(),i.reset()}catch{alert("Помилка при відправленні повідомлення. Будь ласка, спробуйте ще раз.")}});function u(){n.classList.add("visually-hidden"),o.classList.add("visually-hidden"),o.classList.remove("show")}function z(){n.classList.add("visually-hidden"),o.classList.remove("visually-hidden"),o.classList.add("show")}$.addEventListener("click",u);h.addEventListener("click",e=>{e.target===h&&u()});document.addEventListener("keydown",e=>{e.key==="Escape"&&u()});k();
//# sourceMappingURL=commonHelpers2.js.map
