import{t as q,g as C}from"./assets/theme-module-2ca9ef99.js";import{A as F,S as A,N as x,K as M,i as p,a as b,b as I}from"./assets/vendor-27446d2f.js";const j=document.querySelector(".faq__list");new F(j,{elementClass:"faq__item",triggerClass:"faq__btn",panelClass:"ac-panel",activeClass:"is-active",openOnInit:[0],onOpen:e=>{}});const B=document.querySelectorAll('[name="slider"]'),_=document.querySelector(".mob-menu-btn"),T=document.querySelector(".mob-menu-btn-close"),l=document.querySelector(".mob-menu");document.querySelector(".header-nav-menu");const P=document.querySelectorAll('a[href*="#"]');for(let e of P)e.addEventListener("click",function(t){t.preventDefault();const s=e.getAttribute("href").substr(1);document.getElementById(s).scrollIntoView({behavior:"smooth",block:"start"})});for(let e of B)e.addEventListener("click",t=>{q()});_.addEventListener("click",e=>{l.classList.add("is-open")});T.addEventListener("click",e=>{l.classList.remove("is-open")});l.addEventListener("click",e=>{const t=e.target.name;if(t==="About-me"||t==="Projects"||t==="Contacts")l.classList.remove("is-open");else return});const d=document.getElementById("two-button"),N=document.querySelectorAll(".visit-button"),u=document.querySelectorAll("#list-sites .hidden");let r=0;const v=["https://spinkll.github.io/Project-javascript-goit/","https://spinkll.github.io/Project-javascript-goit/good-team","https://klimkovskyi.github.io/CodeCrafters/"];let c=0;function L(){r>=u.length?d.style.display="none":d.style.display="block"}L();d.addEventListener("click",()=>{let e=3;for(let t=r;t<r+e&&t<u.length;t++)u[t].classList.remove("hidden");r+=e,L()});N.forEach(e=>{e.addEventListener("click",function(){const t=v[c];t&&(window.open(t,"_blank"),c=(c+1)%v.length)})});const k=document.querySelector("#swiper-container"),y=new A(".swiper",{modules:[x,M],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,breakpoints:{1280:{slidesPerView:2},0:{slidesPerView:"auto"}},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});document.addEventListener("keydown",e=>{e.key==="Tab"&&k.contains(document.activeElement)&&(e.shiftKey?y.slidePrev():y.slideNext())});const E=document.querySelector(".loader");function R(){E.style.display="none"}function W(){E.style.visibility="visible"}const $="https://portfolio-js.b.goit.study/api/reviews",h=document.querySelector(".swiper-wrapper");async function H(){return(await b.get($,{})).data}function O(e){return e.map(t=>`
      <li class="swiper-slide" id="review-slide">

      <p class="reviews-text">${t.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${t.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${t.avatar_url}"/>
          </a>
          <p class="reviews-name">${t.author}</p>
      </div>
      </li>`).join("")}const f=document.querySelector(".error-container");W();H().then(e=>{f.style.display="none",e.length>0?h.insertAdjacentHTML("beforeend",O(e)):(h.insertAdjacentHTML("beforeend","Not found"),p.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(e=>{k.style.display="none",f.insertAdjacentHTML("beforeend","<p>Not found</p>"),p.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}),console.log(e)}).finally(()=>{R()});const i=document.querySelector(".work-together-form"),a=i.elements.email,V=i.elements.message,o=document.querySelector(".modal"),z=o.querySelector(".button-close"),g=o.querySelector(".modal-backdrop"),w=document.getElementById("email-error"),n=document.querySelector(".icon-email"),D=b.create({baseURL:"https://portfolio-js.b.goit.study/api-docs"});o.classList.add("visually-hidden");n.classList.add("visually-hidden");async function K(e,t){try{return(await D.post("",{email:e,message:t})).data}catch(s){throw s}}function S(e){return/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(e)}i.addEventListener("input",e=>{const t=a.value.trim();n.classList.add("visually-hidden"),S(t)&&n.classList.remove("visually-hidden")});i.addEventListener("submit",async e=>{e.preventDefault();const t=a.value.trim(),s=V.value.trim();if(w.textContent="",a.classList.remove("invalid-input"),t===""||s===""){alert("Будь ласка, заповніть всі поля.");return}if(S(t))n.classList.remove("visually-hidden");else{w.textContent="Invalid email, try again",a.classList.add("invalid-input");return}try{await K(t,s),U(),i.reset()}catch{alert("Помилка при відправленні повідомлення. Будь ласка, спробуйте ще раз.")}});function m(){n.classList.add("visually-hidden"),o.classList.add("visually-hidden"),o.classList.remove("show")}function U(){n.classList.add("visually-hidden"),o.classList.remove("visually-hidden"),o.classList.add("show")}z.addEventListener("click",m);g.addEventListener("click",e=>{e.target===g&&m()});document.addEventListener("keydown",e=>{e.key==="Escape"&&m()});C();I.init();
//# sourceMappingURL=commonHelpers2.js.map
