import{A as v,S as w,N as b,K as L,i as m,a as g}from"./assets/vendor-6128a7b9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const S=document.querySelector(".faq__list");new v(S,{elementClass:"faq__item",triggerClass:"faq__btn",panelClass:"ac-panel",activeClass:"is-active",openOnInit:[0],onOpen:e=>{}});const k=window.matchMedia("(prefers-color-scheme: dark)");function a(e){localStorage.setItem("theme",e),document.documentElement.className=e}function E(){localStorage.getItem("theme")==="theme-dark"?a("theme-light"):a("theme-dark")}function q(){k.matches===!0?(a("theme-dark"),document.getElementById("slider").checked=!0):(a("theme-light"),document.getElementById("slider").checked=!1)}const F=document.querySelector("#slider"),M=document.querySelector(".mob-menu-btn"),C=document.querySelector(".mob-menu-btn-close"),i=document.querySelector(".mob-menu"),A=document.querySelector(".header-nav-menu"),I=document.querySelectorAll('a[href*="#"]');function y(){for(let e of I)e.addEventListener("click",function(t){t.preventDefault();const r=e.getAttribute("href").substr(1);document.getElementById(r).scrollIntoView({behavior:"smooth",block:"start"})})}F.addEventListener("click",e=>{E()});M.addEventListener("click",e=>{i.classList.add("is-open")});C.addEventListener("click",e=>{i.classList.remove("is-open")});A.addEventListener("click",e=>{const t=e.target.name;if(t==="About me"||t==="Projects"||t==="Contacts")y();else return});i.addEventListener("click",e=>{const t=e.target.name;if(t==="About me"||t==="Projects"||t==="Contacts")i.classList.remove("is-open"),y();else return});new w(".swiper",{modules:[b,L],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,breakpoints:{1280:{slidesPerView:2},0:{slidesPerView:"auto"}},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});const x="https://portfolio-js.b.goit.study/api/reviews",p=document.querySelector(".swiper-wrapper");async function O(){return(await g.get(x,{})).data}function _(e){return e.map(t=>`
      <li class="swiper-slide">
      <p class="reviews-text">${t.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${t.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${t.avatar_url}"/>
          </a>
          <p class="reviews-name">${t.author}</p>
      </div>
      </li>`).join("")}const f=document.querySelector(".error-container"),j=document.querySelector(".swiper");O().then(e=>{f.style.display="none",e.length>0?p.insertAdjacentHTML("beforeend",_(e)):(p.insertAdjacentHTML("beforeend","Not found"),m.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(e=>{j.style.display="none",f.insertAdjacentHTML("beforeend","<p>Not found</p>"),m.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}),console.log(e)});const c=document.querySelector(".work-together-form"),B=c.elements.email,P=c.elements.message,n=document.querySelector(".modal"),T=n.querySelector(".button-close"),h=n.querySelector(".modal-backdrop"),N=g.create({baseURL:"https://portfolio-js.b.goit.study/api-docs"});n.classList.add("visually-hidden");async function R(e,t){try{return(await N.post("",{email:e,message:t})).data}catch(r){throw r}}c.addEventListener("submit",async e=>{e.preventDefault();const t=B.value.trim(),r=P.value.trim();if(t===""||r===""){alert("Будь ласка, заповніть всі поля.");return}try{await R(t,r),W(),c.reset()}catch{alert("Помилка при відправленні повідомлення. Будь ласка, спробуйте ще раз.")}});function u(){n.classList.add("visually-hidden"),n.classList.remove("show")}function W(){n.classList.remove("visually-hidden"),n.classList.add("show")}T.addEventListener("click",u);h.addEventListener("click",e=>{e.target===h&&u()});document.addEventListener("keydown",e=>{e.key==="Escape"&&u()});q();
//# sourceMappingURL=commonHelpers.js.map
