import{t as g,g as b}from"./assets/theme-module-4e1d2e84.js";import{A as L,S as k,N as S,K as E,i as d,a as y}from"./assets/vendor-6128a7b9.js";const q=document.querySelector(".faq__list");new L(q,{elementClass:"faq__item",triggerClass:"faq__btn",panelClass:"ac-panel",activeClass:"is-active",openOnInit:[0],onOpen:e=>{}});const F=document.querySelectorAll('[name="slider"]'),M=document.querySelector(".mob-menu-btn"),C=document.querySelector(".mob-menu-btn-close"),r=document.querySelector(".mob-menu");document.querySelector(".header-nav-menu");const x=document.querySelectorAll('a[href*="#"]');for(let e of x)e.addEventListener("click",function(t){t.preventDefault();const o=e.getAttribute("href").substr(1);document.getElementById(o).scrollIntoView({behavior:"smooth",block:"start"})});for(let e of F)e.addEventListener("click",t=>{g()});M.addEventListener("click",e=>{r.classList.add("is-open")});C.addEventListener("click",e=>{r.classList.remove("is-open")});r.addEventListener("click",e=>{const t=e.target.name;if(t==="About me"||t==="Projects"||t==="Contacts")r.classList.remove("is-open");else return});const a=document.getElementById("two-button"),c=document.querySelectorAll("#list-sites .hidden");let n=0;function f(){n>=c.length?a.style.display="none":a.style.display="block"}f();a.addEventListener("click",()=>{let e=3;for(let t=n;t<n+e&&t<c.length;t++)c[t].classList.remove("hidden");n+=e,f()});const h=document.querySelector("#swiper-container"),u=new k(".swiper",{modules:[S,E],speed:400,spaceBetween:20,centeredSlides:!1,centeredSlidesBounds:!0,autoHeight:!0,breakpoints:{1280:{slidesPerView:2},0:{slidesPerView:"auto"}},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});document.addEventListener("keydown",e=>{e.key==="Tab"&&h.contains(document.activeElement)&&(e.shiftKey?u.slidePrev():u.slideNext())});const w=document.querySelector(".loader");function A(){w.style.display="none"}function B(){w.style.visibility="visible"}const I="https://portfolio-js.b.goit.study/api/reviews",m=document.querySelector(".swiper-wrapper");async function T(){return(await y.get(I,{})).data}function _(e){return e.map(t=>`
      <li class="swiper-slide" id="review-slide">

      <p class="reviews-text">${t.review}</p>
      <div class="review-author-data">
          <a class="reviews-img-link" href="${t.avatar_url}">
          <img class="reviews-img" alt="author's avatar" src="${t.avatar_url}"/>
          </a>
          <p class="reviews-name">${t.author}</p>
      </div>
      </li>`).join("")}const p=document.querySelector(".error-container");B();T().then(e=>{p.style.display="none",e.length>0?m.insertAdjacentHTML("beforeend",_(e)):(m.insertAdjacentHTML("beforeend","Not found"),d.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}).catch(e=>{h.style.display="none",p.insertAdjacentHTML("beforeend","<p>Not found</p>"),d.show({message:"Sorry, no reviews found",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}),console.log(e)}).finally(()=>{A()});const i=document.querySelector(".work-together-form"),j=i.elements.email,N=i.elements.message,s=document.querySelector(".modal"),R=s.querySelector(".button-close"),v=s.querySelector(".modal-backdrop"),W=y.create({baseURL:"https://portfolio-js.b.goit.study/api-docs"});s.classList.add("visually-hidden");async function H(e,t){try{return(await W.post("",{email:e,message:t})).data}catch(o){throw o}}i.addEventListener("submit",async e=>{e.preventDefault();const t=j.value.trim(),o=N.value.trim();if(t===""||o===""){alert("Будь ласка, заповніть всі поля.");return}try{await H(t,o),P(),i.reset()}catch{alert("Помилка при відправленні повідомлення. Будь ласка, спробуйте ще раз.")}});function l(){s.classList.add("visually-hidden"),s.classList.remove("show")}function P(){s.classList.remove("visually-hidden"),s.classList.add("show")}R.addEventListener("click",l);v.addEventListener("click",e=>{e.target===v&&l()});document.addEventListener("keydown",e=>{e.key==="Escape"&&l()});b();
//# sourceMappingURL=commonHelpers2.js.map
